version: "1.0"
info:
  model: int-scaffold
packages:
- name: FLOW_TEST_08_08_1Project
  gitServerName: testP1
  gitUrl: https://github.com/PoojaAnandGit
  gitUsername: PoojaAnandGit
  gitBranch: main
